version: '3'
services:
  dynamicbio:
    env_file:
      - .env
    image: warriorzz/dynamicbio
    restart: unless-stopped
    container_name: dynamicbio
    depends_on:
      - mongo
    environment:
      - DATABASE_CONNECTION_STRING=mongodb://root:root@mongo/database?authSource=admin
      - DATABASE_NAME=database
      - OAUTH_ACCESS_TOKEN=
      - OAUTH_ACCESS_SECRET=
      - CONSUMER_ACCESS_TOKEN=
      - CONSUMER_ACCESS_SECRET=
      - DISCORD_API_URL=http://dynamicbiobackend/api/v1
      - ENABLE_DISCORD=true
      - DISCORD_GUILD_ID=
      - DISCORD_USER_ID=
      - DISCORD_SECRET=
    networks:
      - app

  mongo:
    image: mongo
    container_name: dynamicbio_database
    environment:
      - MONGO_INITDB_DATABASE=database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - dynamic_bio:/data/db
    networks:
      - app

volumes:
  dynamic_bio:

networks:
  app:
