version: '3'
services:
  dynamicbio:
    env_file:
      - .env
    image: warriorzz/dynamicbio
    restart: unless-stopped
    container_name: dynamicbio
    depends_on:
      - mongo
    environment:
      - DATABASE_CONNECTION_STRING=
      - DATABASE_NAME=
      - OAUTH_ACCESS_TOKEN=
      - OAUTH_ACCESS_SECRET=
      - CONSUMER_ACCESS_TOKEN=
      - CONSUMER_ACCESS_SECRET=
      - DISCORD_API_URL=
      - ENABLE_DISCORD=true
      - DISCORD_GUILD_ID=
      - DISCORD_USER_ID=
    networks:
      - app

  backend:
    build:
      dockerfile: backend.Dockerfile
    networks:
      - app
    environment:
      - DISCORD_TOKEN=
    ports:
      - 80:80
  mongo:
    image: mongo
    container_name: dynamicbio_database
    environment:
      - MONGO_INITDB_DATABASE=database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - dynamic_bio:/data/db
    networks:
      - app

volumes:
  dynamic_bio:

networks:
  app:
